services:
  # Backend API service
  - type: web
    name: mintmark-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: APTOS_NETWORK
        sync: false
      - key: APTOS_NODE_URL
        sync: false
      - key: CONTRACT_ADDRESS
        sync: false
      - key: MODULE_NAME
        sync: false
      - key: DEVNET_PRIVATE_KEY
        sync: false
      - key: TESTNET_PRIVATE_KEY
        sync: false
      - key: MAINNET_PRIVATE_KEY
        sync: false

  # Frontend web application
  - type: web
    name: mintmark-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: VITE_APTOS_NETWORK
        sync: false
      - key: VITE_APTOS_NODE_URL
        sync: false
      - key: VITE_CONTRACT_ADDRESS
        sync: false
      - key: VITE_MODULE_NAME
        sync: false
      - key: VITE_APP_NAME
        value: Mintmark
      - key: VITE_APP_DESCRIPTION
        value: Decentralized POAP Platform on Aptos
      - key: VITE_API_URL
        fromService:
          name: mintmark-backend
          type: web
          property: url