[package]
name = "mintmark"
version = "0.0.1"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "main" }
AptosTokenObjects = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-token-objects", rev = "main" }

[addresses]
mintmark = "0x69a158813efb20d7f134294ae114184cf6a12269a52106cb5e1d471e4761e4db"